spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${HONOR_PRESERVATION_MAIL}
    password: ${HONOR_PRESERVATION_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false